### ISSUE TITLE
Extension.sendRequest problems

### ISSUE THREAD

**Issue by mikecann** [tong/chrome.extension#4]
Firstly thankyou so much for providing this lib, this really is a great set of externs!

Theres an issue with sendRequest, for some reason it says invalid args when you try to use Extension.sendRequest when you dont know what the Id of the tab is you are sending to. Such a case happens when sending a message from a content script to a background page.

I tried adding an overload for the function like:

@:overload(function(request : Dynamic, responseCallback : Dynamic->Void) : Void{})

Unfortunately this didnt work so the only way was to comment out the line and replace it with:

static function sendRequest(request : Dynamic, responseCallback : Dynamic->Void ) : Void;

This then works great.

**Comment by tong** [comment]
Extension.sendRequest is depricated.
Use: https://developer.chrome.com/extensions/runtime#method-sendMessage
